@extends('lights.layout')
@section('title', 'Administration')
@section('content')
<div class="page-heading"><div><p class="eyebrow">LIGHTS ADMINISTRATION</p><h1>Courts &amp; activity</h1><p class="muted">Monitor the venue, manage pricing and payments, and review account activity.</p></div></div>
<nav class="admin-tabs" role="tablist" aria-label="Administration sections">
@foreach(['overview' => 'Overview', 'settings' => 'Settings', 'members' => 'Members', 'activity' => 'Activity'] as $key => $label)<button type="button" role="tab" id="tab-{{ $key }}" aria-controls="panel-{{ $key }}" aria-selected="{{ $key === 'overview' ? 'true' : 'false' }}" @if($key !== 'overview') tabindex="-1" @endif data-admin-tab="{{ $key }}">{{ $label }}@if($key === 'members') <span class="tab-count">{{ $members->count() }}</span>@endif</button>@endforeach
</nav>

<div role="tabpanel" id="panel-overview" aria-labelledby="tab-overview" data-admin-panel="overview">
<section class="panel" id="service-health"><div class="section-title"><div><h2>Service health</h2><p class="muted">The items that can prevent safe customer operation.</p></div><button class="button secondary" type="button" id="refresh-health" data-url="{{ route('lights.admin.health') }}">Refresh</button></div><div class="health-grid">
<div class="health-item"><strong>Worker</strong><span data-health="worker" class="{{ $healthReport['worker']['healthy'] ? 'ok' : 'bad' }}">{{ $healthReport['worker']['healthy'] ? 'Healthy' : 'Not reporting' }}</span></div>
<div class="health-item"><strong>Shelly</strong><span data-health="hardware" class="{{ ($healthReport['hardware']['online'] ?? false) ? 'ok' : 'bad' }}">{{ ($healthReport['hardware']['online'] ?? false) ? 'Online' : 'Offline' }}</span></div>
<div class="health-item"><strong>Uncertain actions</strong><span data-health="uncertain" class="{{ array_sum([$healthReport['attention']['uncertain_controls'], $healthReport['attention']['uncertain_manual_commands']]) ? 'bad' : 'ok' }}">{{ $healthReport['attention']['uncertain_controls'] + $healthReport['attention']['uncertain_manual_commands'] }}</span></div>
<div class="health-item"><strong>Old PayFast pending</strong><span data-health="payments" class="{{ $healthReport['attention']['payfast_pending_over_one_hour'] ? 'bad' : 'ok' }}">{{ $healthReport['attention']['payfast_pending_over_one_hour'] }}</span></div></div></section>
@if(config('lights.mode') === 'live')<section class="panel"><h2>Live-service readiness</h2><div class="hardware-grid"><div><strong>PayFast</strong><p class="muted">{{ config('lights.payfast.enabled') ? 'Enabled — verified ITNs credit wallets.' : 'Disabled in Settings.' }}</p></div><div><strong>Customer light control</strong><p class="muted">{{ config('lights.control.live_enabled') && config('lights.control.customer_enabled') ? 'Enabled — device timer required before billing.' : 'Locked pending supervised acceptance.' }}</p></div></div></section>@endif
@if(config('lights.shelly_setup')) @include('lights.partials.shelly-status', ['returnTo' => 'admin']) @if(config('lights.control.live_enabled'))<section class="panel action-panel"><div><p class="eyebrow">REAL SHELLY CONTROLS</p><h2>Switch the physical courts</h2><p class="muted">Direct timed ON and explicit OFF controls. Customer wallet sessions remain separately governed.</p></div><a class="button primary" href="{{ route('lights.admin.control') }}">Open court controls</a></section>@endif<p class="setup-link"><a href="{{ route('lights.admin.shelly') }}">Shelly connection settings</a></p>@endif
@if($active->isNotEmpty())<section class="panel"><h2>Demo sessions</h2>@foreach($active as $session)<div class="history-row"><div><strong>{{ $session->court_name }} · {{ $session->member_name }}</strong><small>Simulated · R {{ number_format($session->charged_cents / 100, 2) }} charged</small></div><form method="POST" action="{{ route('lights.admin.stop', $session->id) }}">@csrf<button class="button danger">Stop demo</button></form></div>@endforeach</section>@endif
@if($liveActive->isNotEmpty())<section class="panel"><h2>Live customer sessions</h2>@foreach($liveActive as $session)<div class="history-row"><div><strong>{{ $session->court_name }} · {{ $session->member_name }}</strong><small>{{ str_replace('_', ' ', $session->state) }} · R {{ number_format($session->charged_cents / 100, 2) }} charged</small>@if($session->state === 'review')<small>Billing is frozen. Confirm the physical lights are OFF before releasing this court.</small>@endif</div><div class="admin-member-actions">@if($session->state === 'review')<form method="POST" action="{{ route('lights.admin.control.review', $session->id) }}">@csrf<input type="hidden" name="action" value="off"><button class="button danger">Request OFF again</button></form><form method="POST" action="{{ route('lights.admin.control.review', $session->id) }}">@csrf<input type="hidden" name="action" value="confirmed_off"><label><input type="checkbox" name="physical_off" value="1" required> I physically confirmed OFF</label><button class="button primary">Release court</button></form>@else<form method="POST" action="{{ route('lights.admin.control.stop', $session->id) }}">@csrf<button class="button danger">Emergency OFF</button></form>@endif</div></div>@endforeach</section>@endif
@if($active->isEmpty() && $liveActive->isEmpty())<div class="quiet-state"><strong>No active sessions</strong><span>Both demo and customer session queues are clear.</span></div>@endif
</div>

<div role="tabpanel" id="panel-settings" aria-labelledby="tab-settings" data-admin-panel="settings" hidden>
<section class="panel" id="payfast-settings"><div class="section-title"><div><h2>PayFast</h2><p class="muted">Wallet top-up provider configuration.</p></div><span class="status-pill {{ $payFast['enabled'] ? 'is-ready' : '' }}">{{ $payFast['enabled'] ? ($payFast['sandbox'] ? 'Sandbox enabled' : 'Live enabled') : 'Disabled' }}</span></div><form class="court-form" method="POST" action="{{ route('lights.admin.payfast') }}">@csrf
<label>Payments<select name="enabled"><option value="0" @selected(!$payFast['enabled'])>Disabled</option><option value="1" @selected($payFast['enabled'])>Enabled</option></select></label><label>Environment<select name="sandbox"><option value="1" @selected($payFast['sandbox'])>Sandbox / testing</option><option value="0" @selected(!$payFast['sandbox'])>Live</option></select></label>
@foreach(['merchant_id' => 'Merchant ID', 'merchant_key' => 'Merchant key', 'passphrase' => 'Passphrase'] as $key => $label)<label>{{ $label }} <small>{{ $payFast[$key.'_configured'] ? 'Configured' : 'Not configured' }}</small><input type="password" name="{{ $key }}" autocomplete="new-password" placeholder="Leave blank to keep existing"></label>@endforeach<button class="button primary">Save PayFast settings</button></form><p class="muted settings-footnote">Encrypted at rest. Existing secrets are never displayed. Current source: {{ $payFast['source'] === 'admin' ? 'admin settings' : 'deployment environment' }}.</p></section>
<section class="panel"><h2>Court pricing &amp; channels</h2><p class="muted">Stop an active session before changing its court. A channel can belong to only one court.</p>@foreach($courts->concat([null]) as $court)<details class="court-settings"><summary>{{ $court?->name ?? 'Add another court' }} @if($court)<span>R {{ number_format($court->rate_cents / 100, 2) }}/hour · Channel {{ $court->channel }} · {{ $court->active ? 'Available' : 'Unavailable' }}</span>@endif</summary><form class="court-form" method="POST" action="{{ route('lights.admin.courts') }}">@csrf<input type="hidden" name="court_id" value="{{ $court?->id }}"><label>Court name<input name="name" value="{{ $court?->name }}" required maxlength="100"></label><label>Hourly rate (R)<input name="rate" value="{{ $court ? number_format($court->rate_cents / 100, 2, '.', '') : '60.00' }}" required></label><label>Device label<input name="device_label" value="{{ $court?->device_label ?? 'Shelly Pro 2' }}" required maxlength="80"></label><label>Channel<select name="channel"><option value="0" @selected(($court?->channel ?? 0) == 0)>0</option><option value="1" @selected($court?->channel == 1)>1</option></select></label><label>Availability<select name="active"><option value="1" @selected($court?->active ?? true)>Available</option><option value="0" @selected($court && !$court->active)>Unavailable</option></select></label><button class="button primary">Save court</button></form></details>@endforeach</section>
<section class="panel"><h2>PayFast reconciliation</h2><p class="muted">Recent real requests. Wallet credit requires a verified COMPLETE notification.</p>@forelse($payments as $payment)<div class="history-row"><div><strong>{{ $payment->member_name }}</strong><small>{{ $payment->member_email }} · {{ gmdate('d M Y H:i', $payment->created_at + 7200) }} SAST · {{ $payment->gateway_reference ?: 'no provider reference yet' }}</small></div><strong>{{ strtoupper($payment->status) }} · R {{ number_format($payment->amount_cents / 100, 2) }}</strong></div>@empty<p class="muted">No real PayFast requests yet.</p>@endforelse</section></div>

<div role="tabpanel" id="panel-members" aria-labelledby="tab-members" data-admin-panel="members" hidden>
<section class="panel member-cash-panel">
    <div class="member-cash-heading">
        <div><p class="eyebrow">CASH DESK</p><h2>Find a member and add cash</h2><p class="muted">Search by name or email, confirm the account, then record the cash received.</p></div>
        <div class="member-search-box"><label for="member-search">Find member</label><div class="member-search-control"><span aria-hidden="true">⌕</span><input type="search" id="member-search" placeholder="Type a name or email…" autocomplete="off"><button type="button" id="member-search-clear" aria-label="Clear member search" hidden>Clear</button></div><small><span id="member-result-count">{{ $members->count() }}</span> account{{ $members->count() === 1 ? '' : 's' }}</small></div>
    </div>
    <div class="quiet-state member-search-empty" id="member-search-empty" hidden><strong>No member found</strong><span>Check the spelling or try the member's email address.</span></div>
    <div class="member-list">
    @forelse($members as $member)
        <article class="admin-member" data-member="{{ $member->id }}" data-member-search="{{ Illuminate\Support\Str::lower($member->name.' '.$member->email) }}">
            <header class="member-card-header"><div class="member-avatar" aria-hidden="true">{{ Illuminate\Support\Str::upper(Illuminate\Support\Str::substr($member->name, 0, 1)) }}</div><div class="member-identity"><strong>{{ $member->name }}{{ $member->is_admin ? ' · Admin' : '' }}</strong><span>{{ $member->email }}</span><small>{{ $member->email_verified_at ? 'Verified' : 'Unverified' }} · <span data-member-status>{{ $member->active ? 'Enabled' : 'Disabled' }}</span></small></div><div class="member-wallet"><small>Wallet balance</small><strong data-member-balance>R {{ number_format($member->balance_cents / 100, 2) }}</strong></div></header>
            <form class="cash-topup-form" method="POST" action="{{ route('lights.admin.members.adjustment', $member->id) }}" data-admin-action>@csrf<input type="hidden" name="direction" value="credit"><input type="hidden" name="payment_type" value="cash"><input type="hidden" name="request_key" value="{{ (string) Illuminate\Support\Str::uuid() }}"><label>Cash received (R)<input name="amount" inputmode="decimal" value="10.00" required aria-label="Cash amount for {{ $member->name }}"></label><label>Receipt reference or note<input name="reason" required minlength="5" maxlength="200" placeholder="e.g. Receipt 1042"></label><button class="button primary">Add cash to wallet</button></form>
            <details class="member-more"><summary>Account tools</summary><div class="member-tools"><form method="POST" action="{{ route('lights.admin.members.status', $member->id) }}" data-admin-action>@csrf<input type="hidden" name="active" value="{{ $member->active ? 0 : 1 }}"><button class="button secondary" @disabled($member->is_admin && $member->id === Auth::guard('lights')->id())>{{ $member->active ? 'Disable account' : 'Enable account' }}</button></form><form class="correction-form" method="POST" action="{{ route('lights.admin.members.adjustment', $member->id) }}" data-admin-action>@csrf<input type="hidden" name="request_key" value="{{ (string) Illuminate\Support\Str::uuid() }}"><label>Correction<select name="direction"><option value="credit">Credit</option><option value="debit">Debit</option></select></label><label>Amount (R)<input name="amount" inputmode="decimal" value="10.00" required></label><label>Audit reason<input name="reason" required minlength="5" maxlength="200"></label><button class="button secondary">Record correction</button></form></div></details>
        </article>
    @empty<p class="muted">No client accounts.</p>@endforelse
    </div>
</section>
</div>

<div role="tabpanel" id="panel-activity" aria-labelledby="tab-activity" data-admin-panel="activity" hidden><div class="history-grid"><section class="panel"><h2>Wallet ledger</h2><p class="muted">Latest 50 movements.</p>@forelse($ledger as $entry)<div class="history-row"><div><strong>{{ $entry->name }}</strong><small>{{ $entry->kind }} · {{ gmdate('d M H:i:s', $entry->created_at + 7200) }} SAST</small></div><strong>{{ $entry->amount_cents < 0 ? '−' : '+' }}R {{ number_format(abs($entry->amount_cents) / 100, 2) }}</strong></div>@empty<p class="muted">No wallet movements.</p>@endforelse</section><section class="panel"><h2>Audit events</h2><p class="muted">Latest 50 events. Credentials are never recorded.</p>@forelse($events as $event)<details class="event"><summary>{{ str_replace('_', ' ', $event->kind) }}<small>{{ gmdate('d M H:i:s', $event->created_at + 7200) }} SAST · actor {{ $event->actor_id ?? 'worker' }}</small></summary><code>{{ $event->details }}</code></details>@empty<p class="muted">No events yet.</p>@endforelse</section></div></div>
@endsection
