@extends('layouts.app')
@section('title', 'Configure '.$product->name)
@section('content')
<section class="content-header"><h1>{{ $product->name }}</h1><p>Online presentation and stock buffer; POS remains the source of price and physical stock.</p></section><section class="content">
@if($errors->any())<div class="alert alert-danger"><ul>@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
<form method="post" action="{{ route('shop.admin.catalog.products.update', [$channel, $product]) }}" enctype="multipart/form-data">@csrf @method('PUT')<div class="box box-primary"><div class="box-body">
<div class="form-group"><label>URL slug<input class="form-control" name="slug" value="{{ old('slug', $shopProduct?->slug ?? \Illuminate\Support\Str::slug($product->name.'-'.$product->id)) }}" required></label></div>
<div class="form-group"><label>Short description<textarea class="form-control" name="short_description" maxlength="500">{{ old('short_description', $shopProduct?->short_description) }}</textarea></label></div>
<div class="form-group"><label>Web description<textarea class="form-control" name="web_description" rows="5">{{ old('web_description', $shopProduct?->web_description) }}</textarea></label></div>
<div class="form-group"><label for="online_image">Online display picture</label><div><img src="{{ $shopProduct?->display_image_url ?? $product->image_url }}" alt="Current picture for {{ $product->name }}" style="width: 180px; height: 135px; object-fit: contain; border: 1px solid #ddd; margin-bottom: 10px;"></div><input id="online_image" type="file" name="online_image" class="form-control" accept="image/jpeg,image/png,image/webp" aria-describedby="online-image-help"><p id="online-image-help" class="help-block">Upload a JPG, PNG or WebP image up to 4.8 MB. A new upload replaces the current online picture; if none is uploaded, the POS picture is used.</p></div>
<label><input type="checkbox" name="featured" value="1" @checked(old('featured', $shopProduct?->featured))> Featured</label> <label><input type="checkbox" name="published" value="1" @checked(old('published', (bool) $shopProduct?->published_at && !$shopProduct?->unpublished_at))> Published online</label>
<input type="hidden" name="sort_order" value="{{ old('sort_order', $shopProduct?->sort_order ?? 0) }}">
<h3>Variations</h3><div class="table-responsive"><table class="table table-bordered"><thead><tr><th>POS variation</th><th>Price</th><th>Stock</th><th>Online</th><th>Display name</th><th>Safety stock</th><th>Max/order</th></tr></thead><tbody>
@foreach($product->variations as $variation)@php($saved = $shopProduct?->variations?->firstWhere('variation_id', $variation->id))@php($stock = $variation->variation_location_details->first()?->qty_available ?? 0)<tr><td>{{ $variation->product_variation?->name }} {{ $variation->name }}</td><td>R {{ number_format($variation->sell_price_inc_tax, 2) }}</td><td>{{ $stock }}</td><td><input type="checkbox" name="variations[{{ $variation->id }}][published]" value="1" @checked(old('variations.'.$variation->id.'.published', $saved?->published))></td><td><input class="form-control" name="variations[{{ $variation->id }}][display_name]" value="{{ old('variations.'.$variation->id.'.display_name', $saved?->display_name) }}"></td><td><input class="form-control" type="number" step="1" min="0" name="variations[{{ $variation->id }}][safety_stock]" value="{{ old('variations.'.$variation->id.'.safety_stock', $saved?->safety_stock ?? 0) }}" required><input type="hidden" name="variations[{{ $variation->id }}][sort_order]" value="{{ $saved?->sort_order ?? 0 }}"></td><td><input class="form-control" type="number" step="1" min="1" name="variations[{{ $variation->id }}][maximum_order_quantity]" value="{{ old('variations.'.$variation->id.'.maximum_order_quantity', $saved?->maximum_order_quantity) }}"></td></tr>@endforeach
</tbody></table></div></div><div class="box-footer"><button class="btn btn-primary">Save online product</button> <a class="btn btn-default" href="{{ route('shop.admin.catalog.products', $channel) }}">Back</a></div></div></form></section>
@endsection
