@extends('layouts.app')
@section('title','Cycle count')
@section('content')
<section class="content-header"><h1>{{$count->name}} <small>{{$count->location->name}} · {{$count->status}}</small></h1></section>
<section class="content">@if($errors->any())<div class="alert alert-danger">{{$errors->first()}}</div>@endif
@if($count->status==='draft')<div class="box box-primary"><div class="box-body"><label>Scan barcode or SKU</label><div class="input-group"><input id="stock_count_barcode" class="form-control input-lg" autocomplete="off" autofocus><span class="input-group-btn"><button id="stock_count_scan" class="btn btn-primary btn-lg">Add one</button></span></div><p id="scan_status" class="help-block">A hardware scanner can scan continuously. Each successful scan adds one.</p></div></div>@endif
<form method="POST" action="{{route('inventory-control.counts.update',$count->uuid)}}">@csrf @method('PUT')<div class="box box-default"><div class="box-body table-responsive"><table class="table table-bordered"><thead><tr><th>Product</th><th>SKU</th><th>System snapshot</th><th>Counted</th><th>Variance</th></tr></thead><tbody>@foreach($count->lines as $line)<tr id="count-line-{{$line->id}}"><td>{{$line->product->name}}</td><td>{{$line->variation->sub_sku}}</td><td class="system-qty">{{$line->system_quantity}}</td><td><input class="form-control counted-qty" type="number" step="0.0001" min="0" name="lines[{{$line->id}}]" value="{{$line->counted_quantity}}" required @disabled($count->status!=='draft')></td><td class="variance">{{$line->counted_quantity===null?'Not counted':(float)$line->counted_quantity-(float)$line->system_quantity}}</td></tr>@endforeach</tbody></table></div></div>@if($count->status==='draft')<button class="btn btn-primary">Save count without posting</button>@endif</form>
@if($count->status==='draft')<form method="POST" action="{{route('inventory-control.counts.post',$count->uuid)}}" style="display:inline" onsubmit="return confirm('Post every variance to stock? This cannot be edited afterwards.');">@csrf<button class="btn btn-danger">Review complete — post variances</button></form> <form method="POST" action="{{route('inventory-control.counts.discard',$count->uuid)}}" style="display:inline" onsubmit="return confirm('Discard this count without changing stock?');">@csrf<button class="btn btn-default">Discard count</button></form>@endif <a href="{{route('inventory-control.index')}}" class="btn btn-default">Back</a>
</section>
@endsection
@section('javascript')
<script>
(function(){var input=$('#stock_count_barcode'); function scan(){var code=input.val().trim();if(!code)return;$.post('{{route('inventory-control.counts.scan',$count->uuid)}}',{_token:'{{csrf_token()}}',barcode:code}).done(function(r){var row=$('#count-line-'+r.line_id);row.find('.counted-qty').val(r.counted_quantity);row.find('.variance').text((r.counted_quantity-parseFloat(row.find('.system-qty').text())).toFixed(4));$('#scan_status').text('Added '+r.name);input.val('').focus();}).fail(function(x){$('#scan_status').text((x.responseJSON&&x.responseJSON.message)||'Scan failed').addClass('text-danger');input.select();});} $('#stock_count_scan').on('click',scan);input.on('keydown',function(e){if(e.key==='Enter'){e.preventDefault();scan();}});})();
</script>
@endsection
