@extends('layouts.app')
@section('title','Stock control')
@section('content')
<section class="content-header"><h1>Stock control <small>Replenishment and cycle counts</small></h1></section>
<section class="content">
@include('layouts.partials.error')
<div class="box box-primary"><div class="box-header"><h3 class="box-title">Reorder recommendations</h3><p class="help-block">Suggestions use recent final sales, stock on hand, open purchase orders, supplier lead time and safety stock. Saving settings never creates a purchase order.</p></div><div class="box-body">
<form method="GET" class="form-inline"><label>Location</label> {!! Form::select('location_id',$locations,$locationId,['class'=>'form-control']) !!} <label>Sales window</label><select name="days" class="form-control"><option value="30">30 days</option><option value="60">60 days</option><option value="90">90 days</option></select> <button class="btn btn-default">Recalculate</button></form>
<hr><form method="POST" action="{{route('inventory-control.policies')}}">@csrf<input type="hidden" name="location_id" value="{{$locationId}}"><input type="hidden" name="days" value="{{request('days',30)}}"><div class="table-responsive"><table class="table table-bordered table-condensed"><thead><tr><th>Buy</th><th>Product</th><th>On hand</th><th>Daily sales</th><th>Days cover</th><th>Open PO</th><th>Order qty</th><th>Supplier</th><th>Lead days</th><th>Safety days</th><th>MOQ</th><th>Multiple</th></tr></thead><tbody>
@forelse($recommendations as $i=>$row)<tr><td><input type="checkbox" name="selected[{{$row->variation_id}}]" value="1"></td><td>{{$row->name}}<br><small>{{$row->sub_sku}}</small><input type="hidden" name="policies[{{$i}}][variation_id]" value="{{$row->variation_id}}"></td><td>{{number_format($row->qty_available,2)}}</td><td>{{number_format($row->daily_sales,2)}}</td><td>{{$row->days_cover===null?'No sales':number_format($row->days_cover,1)}}</td><td>{{number_format($row->open_po,2)}}</td><td><input class="form-control input-sm" name="quantity[{{$row->variation_id}}]" type="number" step="0.0001" min="0.0001" value="{{$row->suggested_order}}"></td><td>{!! Form::select("supplier[$row->variation_id]",$suppliers,$row->supplier_id,['class'=>'form-control input-sm policy-supplier','placeholder'=>'Choose','data-policy-target'=>"policy-supplier-$i"]) !!}{!! Form::hidden("policies[$i][supplier_id]",$row->supplier_id,['id'=>"policy-supplier-$i"]) !!}</td><td><input class="form-control input-sm" type="number" min="0" name="policies[{{$i}}][lead_time_days]" value="{{$row->lead_time_days}}"></td><td><input class="form-control input-sm" type="number" min="0" name="policies[{{$i}}][safety_stock_days]" value="{{$row->safety_stock_days}}"></td><td><input class="form-control input-sm" type="number" step="0.0001" min="0.0001" name="policies[{{$i}}][minimum_order_quantity]" value="{{$row->minimum_order_quantity}}"></td><td><input class="form-control input-sm" type="number" step="0.0001" min="0.0001" name="policies[{{$i}}][order_multiple]" value="{{$row->order_multiple}}"></td></tr>
@empty<tr><td colspan="11" class="text-center text-muted">No products currently require replenishment.</td></tr>@endforelse
</tbody></table></div>@can('purchase_order.create')<button class="btn btn-default" type="submit">Save replenishment settings</button> <button class="btn btn-primary" type="submit" formaction="{{route('inventory-control.replenishment.preview')}}">Preview selected purchase orders</button>@endcan</form></div></div>

<div class="row"><div class="col-md-5">@can('purchase.create')<div class="box box-success"><div class="box-header"><h3 class="box-title">Start a cycle count</h3></div><div class="box-body"><form method="POST" action="{{route('inventory-control.counts.create')}}">@csrf<div class="form-group"><label>Name</label><input name="name" required class="form-control" placeholder="e.g. September rack count"></div><div class="form-group"><label>Location</label>{!! Form::select('location_id',$locations,$locationId,['class'=>'form-control','required']) !!}</div><div class="form-group"><label>Notes</label><textarea name="notes" class="form-control"></textarea></div><button class="btn btn-success">Create count snapshot</button></form></div></div>@endcan</div>
<div class="col-md-7"><div class="box box-default"><div class="box-header"><h3 class="box-title">Recent counts</h3></div><div class="box-body table-responsive"><table class="table"><thead><tr><th>Name</th><th>Location</th><th>Status</th><th>Started</th></tr></thead><tbody>@foreach($counts as $count)<tr><td><a href="{{route('inventory-control.counts.show',$count->uuid)}}">{{$count->name}}</a></td><td>{{$count->location->name}}</td><td>{{$count->status}}</td><td>{{$count->created_at}}</td></tr>@endforeach</tbody></table></div></div></div></div>
<div class="box box-default"><div class="box-header"><h3 class="box-title">Recent governed price changes</h3></div><div class="box-body table-responsive"><table class="table table-condensed"><thead><tr><th>When</th><th>Product</th><th>Cost</th><th>Selling price</th><th>Source</th><th>Approved by</th><th>Reason</th></tr></thead><tbody>@forelse($priceChanges as $change)<tr><td>{{$change->created_at}}</td><td>{{$change->variation->product->name}} · {{$change->variation->sub_sku}}</td><td>{{$change->old_cost}} → {{$change->new_cost}}</td><td>{{$change->old_sell_price}} → {{$change->new_sell_price}}</td><td>{{$change->source}}</td><td>{{optional($change->user)->first_name ?: 'System'}}</td><td>{{$change->reason}}</td></tr>@empty<tr><td colspan="7" class="text-center text-muted">No governed price changes recorded yet.</td></tr>@endforelse</tbody></table></div></div>
</section>
@endsection
@section('javascript')<script>$(document).on('change','.policy-supplier',function(){$('#'+$(this).data('policy-target')).val(this.value);});</script>@endsection
