@extends('shop.layout', ['channel' => app(\App\Shop\CatalogService::class)->channel()])
@section('title', 'My account')
@section('content')
<header class="account-heading"><div><p class="eyebrow">MY ACCOUNT</p><h1>Welcome, {{ $customer->name }}</h1></div><form method="POST" action="{{ route('shop.account.logout') }}">@csrf<button class="link-button">Log out</button></form></header>
@if(session('status'))<div class="shop-notice">{{ session('status') }}</div>@endif
@if($pendingLinks)<div class="shop-notice">Your existing in-shop account match is awaiting staff verification. No balance is visible until it is approved.</div>@endif
<section class="account-summary"><div><span>Amount owed in shop</span><strong>R {{ number_format($totalDue, 2) }}</strong></div><div><span>Linked shop accounts</span><strong>{{ $links->count() }}</strong></div><div><span>Online orders</span><strong>{{ $orders->count() }}</strong></div></section>
<section class="account-section"><h2>In-shop invoices</h2><div class="account-table-wrap"><table class="account-table"><thead><tr><th>Invoice</th><th>Date</th><th>Shop</th><th>Total</th><th>Outstanding</th><th></th></tr></thead><tbody>
@forelse($invoices as $invoice)<tr><td data-label="Invoice">{{ $invoice->invoice_no ?: '#'.$invoice->id }}</td><td data-label="Date">{{ \Carbon\Carbon::parse($invoice->transaction_date)->format('Y-m-d') }}</td><td data-label="Shop">{{ $invoice->portal_business_name }}</td><td data-label="Total">R {{ number_format($invoice->final_total, 2) }}</td><td data-label="Outstanding"><strong>R {{ number_format($invoice->portal_balance, 2) }}</strong></td><td>@if(in_array((int) $invoice->id, $activeTransactionIds, true))<span>Payment verification pending</span>@elseif($invoice->portal_balance > 0 && config('shop.account_payments_enabled'))<form method="POST" action="{{ route('shop.account.invoices.pay', $invoice) }}">@csrf<button class="shop-button small">Pay invoice</button></form>@endif</td></tr>@empty<tr><td colspan="6">No in-shop invoices are linked to this account.</td></tr>@endforelse
</tbody></table></div></section>
<section class="account-section"><h2>Online orders</h2><div class="account-grid">@forelse($orders as $order)<article><strong>{{ $order->order_number }}</strong><span>{{ $order->created_at->format('Y-m-d') }}</span><span>R {{ number_format($order->total_cents / 100, 2) }}</span><span>{{ ucfirst(str_replace('_', ' ', $order->order_status)) }}</span><a href="{{ route('shop.account.orders.show', $order->uuid) }}">Open order</a></article>@empty<p>No online orders yet.</p>@endforelse</div></section>
<section class="account-section"><h2>Lights</h2><p>Lights accounts and wallet balances remain separate. Use the Lights portal for top-ups and court sessions.</p></section>
@endsection
